"""Render a `ListView` from the scope graph into an assessor-ready workbook.

Every generated list carries a provenance header — control id, generated
timestamp, and a note that it was projected from the live scope graph — so the
output is defensible at assessment time rather than "someone edited a sheet."
"""

from __future__ import annotations

from datetime import UTC, datetime
from io import BytesIO
from pathlib import Path

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from .catalog import ListView
from .domain import CanonicalEntity

_HEADER_FILL = PatternFill("solid", fgColor="1F3B4D")
_TITLE_FONT = Font(bold=True, size=13, color="1F3B4D")
_META_FONT = Font(italic=True, size=9, color="555555")
_COLHEAD_FONT = Font(bold=True, color="FFFFFF")


def render_view(
    view: ListView,
    entities: list[CanonicalEntity],
    out_path: str | Path,
    generated_by: str = "WinGRC",
) -> Path:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(render_view_bytes(view, entities, generated_by))
    return out


def render_view_bytes(
    view: ListView,
    entities: list[CanonicalEntity],
    generated_by: str = "WinGRC",
) -> bytes:
    """The workbook as bytes, never touching the filesystem.

    The HTTP export uses this rather than render_view(): it once wrote to
    `tempdir/{view_id}.xlsx`, one path shared by every org, so a response
    still streaming could serve a file another tenant's export had just
    overwritten. Rendering in memory removes the shared resource rather
    than narrowing the window.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = view.sheet_title[:31]

    rows = [e for e in entities if e.entity_type == view.entity_type]

    ws["A1"] = view.title
    ws["A1"].font = _TITLE_FONT
    ws["A2"] = "CMMC Practice / NIST 800-171: " + " / ".join(view.control_ids)
    ws["A2"].font = _META_FONT
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    ws["A3"] = (
        f"Generated by {generated_by} on {generated} "
        f"from the live scope graph ({len(rows)} record(s))."
    )
    ws["A3"].font = _META_FONT

    header_row_num = 5
    for col_idx, (_, display) in enumerate(view.columns, start=1):
        cell = ws.cell(row=header_row_num, column=col_idx, value=display)
        cell.font = _COLHEAD_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(horizontal="center", wrap_text=True)

    for r_offset, entity in enumerate(rows, start=header_row_num + 1):
        for col_idx, (attr_key, _) in enumerate(view.columns, start=1):
            value = entity.attributes.get(attr_key, "")
            ws.cell(row=r_offset, column=col_idx, value=_stringify(value))

    for col_idx, (_, display) in enumerate(view.columns, start=1):
        width = max(len(display) + 2, 14)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(width, 40)

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def _stringify(value) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%d")
    return str(value)
